### ISSUE TITLE
E_FAIL has been mistakenly written as E_FAILED

### ISSUE THREAD

**Issue by RangerCD** [NERvGear/NERvSDK#3]
> NERvSDK/include/NERvGear/interface/IExecute.h(36)
> 
> <pre><code>    /// \retval E_FAILED Failed, system continues search the filter chain.</code></pre>

It seems to be E_FAIL instead of E_FAILED.

**Comment by ghost** [comment]
Hello, looks like it must be E_FAIL:
NERvSDK/include/NERvGear/COM.h(74)
    E_FAIL          = 0x80004005L,
