### ISSUE TITLE
希望能够开源其他几个插件

### ISSUE THREAD

**Issue by Krysl** [NERvGear/NERvSDK#4]
现有的那两个插件太过简单，希望多开源几个插件（如HP Bar等等）以供学习。
现有的文档实在是太少了啊，API怎么用真是难以理解，估计GPBeta你最近也没多少空余时间来写文档，所以希望能通过阅读复杂点的插件源码来加深理解。

**Comment by GPBeta** [comment]
由于目前 GUI 的相关 API 暂不开放, 所以 HP-Bar 插件就算公开源代码, 也没有太大意义. 同样如果想写桌面挂件, 目前不依赖第三方 GUI 库的话,就只能直接使用 win32 API 了.
其实整个框架都是参考跟发扬光大 COM 的 组件 和 接口...达到插件跟插件间的协同工作.
API 的 Reference 也正在编写制作中, 稍后会添加到 SDK 的仓库中去.

**Comment by Krysl** [comment]
好吧，预感成真了。原本还想写个能在3D界面显示的插件，看来近期不太可能了啊。说实话，这样一下子就缺了好多动力啊。还得去学个wxWidgets之类的……
顺便问下，GUI相关API预期什么时候开放？

**Comment by GPBeta** [comment]
GUI 相关的 API 将会在设计成熟之后再放出, 所以可能时间会稍长一些.
但是在这之前, 会先加入一款 Web View 支持插件, 顺带提供一个 Web Window 组件, 到时候其他开发者可以直接用 html + css + js 开发 2D/3D 的界面了.
